### ISSUE TITLE
Not all artifacts available from Maven Central

### ISSUE THREAD

**Issue by chkal** [jboss/jboss-test-audit#8]
For some reason not all artifacts are available from Maven Central. It seems like there are only the API and Parent jars available. See the corresponding list [here](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jboss.test-audit%22).

Is there any special reasons for that?

**Comment by gunnarmorling** [comment]
Hey, I'm not sure why some are in Central and others are not, but you
should find everything in the JBoss Maven repo. I recommend you add this
repo in your settings.xml. You can take a look at our example settings.xml
we use with the Bean Validation TCK:
https://github.com/beanvalidation/beanvalidation-tck/blob/master/settings-example.xml
.

**Comment by chkal** [comment]
Thanks @gunnarmorling. I already found everything I need here:

https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/test-audit/

It's just that having to add repositories to `settings.xml` requires manual setup for every developer and complicates setup on CI servers, etc. And because "most" artifacts were already on Maven Central, I was just wondering if there is any special reason for that.

**Comment by gunnarmorling** [comment]
I'm not sure whether it's a goal to have all the audit infrastructure on
Maven Central, as it's something for a very specific audience. I think the
best thing for you to do is to provide a settings.xml as part of the
project (as we e.g. do it in the BV TCK), and point in your README to
always build with -s settings-example.xml. That way it's no effort for
every developer (apart from giving this option of course).

**Comment by mkouba** [comment]
You can also add jboss repo to your pom, no special settings.xml needed.

**Comment by gunnarmorling** [comment]
Well, unless that pom.xml is going to be deployed to Maven Central or any
other public repo. Having repos in (deployed) pom.xml is generally
considered a bad practice and I think the checks on Maven Central would
even disallow it.

**Comment by mkouba** [comment]
@gunnarmorling I see your point, but...

> Having repos in (deployed) pom.xml is generally considered a bad practice...

That would mean that the only "legal" source of dependencies could be Maven Central...

> Maven Central would even disallow it

I'm not quite sure but at least few JBoss projects I know (including Weld) declared repos in their poms until recently ;-)

**Comment by chkal** [comment]
>>  Maven Central would even disallow it
> 
> I'm not quite sure but at least few JBoss projects I know (including Weld) declared repos in their poms until recently ;-)

IIRC this rule was even enforced when deploying to Sonatype OSS repository. But maybe this isn't the case any more.

**Comment by chkal** [comment]
I found this statement in the [Central Component Requirements](http://central.sonatype.org/pages/requirements.html):

> These are the requirements for the pom file. In addition we discourage the usage of `<repositories>` and `<pluginRepositories>` and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.

So it looks like it is not actually forbidden, but just not recommended.

**Comment by chkal** [comment]
But feel free to close this issue if you think that consistent publishing to Maven Central isn't a priority for the project. I somehow agree that this project has a very special target audience and therefore publishing to Central isn't that important.

**Comment by Arpiz-18** [comment]
Hello , I am very new to this platform and is not getting things properly. Please if anyone can help me join the community and the people in the organization and starting my contribution to open source .

**Comment by keilw** [comment]
@gunnarmorling I think that @chkal was onto something because I tried to fully get rid of Bintray which will die on Saturday and the build of [Unit-TCK](https://github.com/unitsofmeasurement/unit-tck) FAILS, check the [Circle CI build job](https://app.circleci.com/pipelines/github/unitsofmeasurement/unit-tck/30/workflows/7505c94f-2072-49ee-8b6f-81bd560475e2/jobs/346) or https://github.com/unitsofmeasurement/unit-tck/issues/40

If you're unwilling or unable to deploy it to MavenCentral, where shall we add the extra JBoss repositories, does it only work in the `settings.xml` or also the `pom.xml`?

**Comment by manovotn** [comment]
`setting.xml` is a global configuration for all projects whereas putting it into `pom.xml` only affects given project.
Therefore, adding it just into `pom.xml` should do the trick.

**Comment by keilw** [comment]
@manovotn Thanks then while I'm not entirely sure, why it could not go there like it was on Bintray, that seems better for a CI setting since each repository has its own `setting.xml` anyway.

**Comment by Ladicek** [comment]
We recently managed to push all JBoss Test Audit artifacts into Central, irrespective of this issue (CC @manovotn). So this issue can IMHO be closed.
